/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_uni_stuttgart_isa_liquidsvm_SVM */

#ifndef _Included_de_uni_stuttgart_isa_liquidsvm_SVM
#define _Included_de_uni_stuttgart_isa_liquidsvm_SVM
#ifdef __cplusplus
extern "C" {
#endif
#undef de_uni_stuttgart_isa_liquidsvm_SVM_serialVersionUID
#define de_uni_stuttgart_isa_liquidsvm_SVM_serialVersionUID 1LL
/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_cover_dataset
 * Signature: (II[D)[I
 */
JNIEXPORT jintArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1cover_1dataset
  (JNIEnv *, jclass, jint, jint, jdoubleArray);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    default_params
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_default_1params
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_init
 * Signature: ([D[D)I
 */
JNIEXPORT jint JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1init
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_train
 * Signature: (I[Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1train
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_select
 * Signature: (I[Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1select
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_test
 * Signature: (I[Ljava/lang/String;I[D[DLde/uni_stuttgart/isa/liquidsvm/ResultAndErrors;)Lde/uni_stuttgart/isa/liquidsvm/ResultAndErrors;
 */
JNIEXPORT jobject JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1test
  (JNIEnv *, jclass, jint, jobjectArray, jint, jdoubleArray, jdoubleArray, jobject);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_clean
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1clean
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    set_param
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_set_1param
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    get_param
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_get_1param
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    get_config_line
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_get_1config_1line
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_get_cover
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1get_1cover
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_get_solution_svs
 * Signature: (IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1get_1solution_1svs
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_get_solution_coeffs
 * Signature: (IIII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1get_1solution_1coeffs
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_write_solution
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1write_1solution
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_uni_stuttgart_isa_liquidsvm_SVM
 * Method:    svm_read_solution
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_uni_1stuttgart_isa_liquidsvm_SVM_svm_1read_1solution
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
